--GO
--CREATE DATABASE NAZAR_SUPER_SHOP_2000
--GO
--CREATE TABLE Users
--(Id INT MASKED WITH(FUNCTION='default()') NOT NULL PRIMARY KEY IDENTITY(1,1),
--[Name] NVARCHAR(50) MASKED WITH(FUNCTION='partial(1,"XXX",1)') NOT NULL CHECK([Name] != ''),
--Email NVARCHAR(50) MASKED WITH(FUNCTION='email()') NOT NULL CHECK(Email !=''),
--Phone NVARCHAR(15) MASKED WITH(FUNCTION='partial(2,"XXXX",2)') NOT NULL DEFAULT 'NONE',
--Salary INT MASKED WITH(FUNCTION='default()') NOT NULL DEFAULT 0,
--[Address] NVARCHAR(90) MASKED WITH(FUNCTION='default()') NOT NULL,
--[Birth Date] DATE MASKED WITH(FUNCTION='default()') NOT NULL
--)
--GO
--INSERT Users
--VALUES
--('ROB','RAZRUSHITEL@SUPERMAIL.HJK','+2345432123',1222,'St.Pushkina,B.Colotushkina','2019-02-02'),
--('ROH','RAZRUSHITEL1000@SUPERMAIL.HJK','+23454322123',1122,'St.Pushkina,B.Colotushkina','2019-02-02')
GO
CREATE USER PLOTVA WITHOUT LOGIN
GO
revert
GRANT SELECT ON dbo.Users TO PLOTVA
GO
EXECUTE AS USER='PLOTVA'
SELECT *
FROM Users
GO
ALTER TABLE Users
--ALTER COLUMN Phone ADD MASKED WITH(FUNCTION='partial(1,"XXXX",1)'),
ALTER COLUMN Phone ADD MASKED WITH(FUNCTION='partial(1,"XXXX",1)')
GO
GRANT UNMASK TO PLOTVA