SELECT [Id]
      ,[Name]
      ,[Surname]
      ,[Patronymic]
      ,[Sex]
      ,[Phone]
      ,[Email]
      ,[Birth Date]
      ,[EmploymentDate]
      ,[PositionId]
  FROM [BarberShop].[dbo].[Barbers]